Use docker compose for development
presslabs/gitium-base pull request #28
Opened 2022-11-23 14:35 UTC by rstefan1

2022-11-23 14:58 UTC, rstefan1 commented
FIXES ENG-336

2022-11-23 14:58 UTC, rstefan1 commented on docker-compose.yaml
> +    image: TODO
Add the image

2022-11-24 15:35 UTC, AMecea requested changes

2022-11-24 15:35 UTC, AMecea commented on wp-config-docker-compose.php
> +    define( 'WP_SITEURL', rtrim( getenv( 'WP_SITEURL' ), '/' ) ?: WP_HOME . '/wp' );
Should work without `/wp/` prefix.

```suggestion
    define( 'WP_SITEURL', rtrim( getenv( 'WP_SITEURL' ), '/' ) ?: WP_HOME  );
```

2022-11-24 15:35 UTC, AMecea commented on wp-config-docker-compose.php
> +    define( 'DISALLOW_FILE_EDIT', "true" === strtolower( getenv( 'DISALLOW_FILE_EDIT' ) ?: "true" ) );
```suggestion
    define( 'DISALLOW_FILE_EDIT', "true" === strtolower( getenv( 'DISALLOW_FILE_EDIT' ) ?: "false" ) );
```

2022-11-24 15:35 UTC, AMecea commented on wp-config-docker-compose.php
> +    define( 'DISALLOW_FILE_MODS', "true" === strtolower( getenv( 'DISALLOW_FILE_MODS' ) ?: "true" ) );
```suggestion
    define( 'DISALLOW_FILE_MODS', "true" === strtolower( getenv( 'DISALLOW_FILE_MODS' ) ?: "false" ) );
```

2022-11-24 15:50 UTC, AMecea requested changes

2022-11-24 15:50 UTC, AMecea commented on wp-config-docker-compose.php
> +if ( 'on' === $_SERVER['HTTPS'] ) {
I see in logs the following warning:
```
[24-Nov-2022 15:39:21 UTC] PHP Warning:  Undefined array key "HTTPS" in /app/web/wp-config.php on line 88
```

Maybe we should  force `http://`.

2022-11-24 15:50 UTC, AMecea commented on docker-compose.yaml
> +      WP_ENV: development
Local network is slower than cloud and 30s of timeout is not enough. 

```suggestion
      WP_ENV: development
      PHP_REQUEST_TIMEOUT: 60

```

2022-11-24 18:21 UTC, cristianuibar requested changes
Please remove the `provision` folder. It is no longer needed as well as [.gitmodules](https://github.com/presslabs/gitium-base/blob/master/.gitmodules).

In the readme docs please remove the step to apply `git submodule update --init` as that's not required anymore.

Also, please make sure the default NGINX timeout is set at minimum 300s.

2023-02-13 09:31 UTC, AMecea requested changes

2023-02-13 09:32 UTC, AMecea commented on wp-config-docker-compose.php
> +    $_SERVER['HTTPS'] = 'on';
There are some PHP warnings:
```
PHP Warning:  Undefined array key "HTTPS" in /app/web/wp-config.php on line 88
```

2023-02-13 09:50 UTC, AMecea requested changes
Please check [this version of docker-compose.yaml](https://github.com/presslabs/gitium-base/commit/82b0e104542a03cffb89120c7fffde81ea1a800c) that works on both linux and mac but on mac requires running with `USER_ID="$(id -u)" GROUP_ID="$(id -g)"`.

2023-02-17 17:24 UTC, AMecea requested changes

2023-02-17 17:24 UTC, AMecea commented on docker-compose.yaml
> +    user: "${USER_ID}:${GROUP_ID}"
```suggestion
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"

```

2023-02-21 10:30 UTC, AMecea approved these changes

2023-02-21 21:59 UTC, AMecea requested changes

2023-02-21 21:59 UTC, AMecea commented on docker-compose.yaml
> +    image: memcached:1.5
```suggestion
    image: memcached:1.6
```

2023-02-21 22:55 UTC, AMecea requested changes

2023-02-21 22:55 UTC, AMecea commented on wp-config-docker.php
> +define('WP_ENV', getenv('WP_ENV') ?: 'production');
```suggestion
define('WP_ENV', getenv('WP_ENV') ?: 'development');
```

2023-02-21 22:55 UTC, AMecea commented on wp-config-docker.php
> +
We need a new category for error reporting. Set by default to output all errors.

```suggestion
/**
 * Error reporting
 **/
 error_reporting(E_ALL);
```

2023-03-28 18:40 UTC, AMecea approved these changes
LGTM. Please squash commits and merge.

2023-03-28 18:40 UTC, AMecea commented on docker-compose.yaml
> +      WP_SITEURL: http://localhost:8080
Let's test without them. Those should not be set.

2023-03-29 12:02 UTC, rstefan1 commented
Change image: `docker.io/presslabs/wordpress-runtime:classic-6.1-php-8.0`

2023-04-18 09:35 UTC, AMecea commented on docker-compose.yaml
> +      WP_ENV: development
```suggestion
      WP_ENVIRONMENT_TYPE: development
```

2023-04-18 09:39 UTC, AMecea approved these changes

2023-04-20 07:52 UTC, merged